services:
  tposts:
    container_name: tposts
    build:
      context: .
      args:
        ENV: dev
    env_file: .env
    environment:
      DEBUG: True
    entrypoint: "/usr/local/tposts/entrypoint.dev.sh"
    ports:
      - ${SERVER_PORT}:8000
    volumes:
      - ./src:/usr/local/tposts/src
    depends_on: 
      - db
  db:
    container_name: tposts-db
    image: postgres
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: tposts
    ports:
      - 5432:5432
